--  1. Find average spending by gender.
-- ans
select gender,round(avg(total_sale),2) as tot_sale from sales_data
group by gender;



--  2. Calculate total revenue generated by each age group.
-- ans
select sum(total_sale),
case
when age between 18 and 25 then "age 18-25"
when age between 26 and 40  then "age 26-40"
when age between 41 and 60 then "age 41-60"
else "age 60+"
end  as group_age from sales_data
group by group_age
order by group_age asc;

--  3. Identify the most popular category (by quantity sold).
-- ans
select sum(quantiy) as tot_qty,category from sales_data
group by category
order by tot_qty desc
limit 1;

--  4. Find the average quantity purchased per transaction.
-- ans
select transactions_id,round(avg(quantiy),1) as avg_qty from sales_data
group by transactions_id;

--  5. Identify customers with highest single purchase.
-- ans


select customer_id, total_sale
from sales_data
order by total_sale desc
limit 1;

--  6. Find total sales generated by male vs female customers.
-- ans

select
 sum(case  when gender='male' then total_sale else 0 end ) as male_sales ,
sum(case when  gender='female' then total_sale else 0 end) as female_sales
from sales_data;


--  7. Identify the age group contributing most revenue.
-- ans


select age_group,SUM(total_sale) AS total_revenue from (select total_sale,
case when age BETWEEN 18 and 25 Then 'age 18 to 25'
when age BETWEEN 26 and 40 Then"age 26 to 40"
When age BETWEEN 41 And 60 then 'age 41 to 60'
Else 'age 60+'
end AS age_group
From sales_data
) t group by age_group
order by total_revenue desc
LImit 1;

--  8. Find categories with highest average sale value.
-- ans

select * from (
select category,round(avg(total_sale),2) as avg_sale from sales_data
group by category ) t
order by avg_sale desc
limit 1;


--  9. Identify customers who purchased more than 10 items in total.
-- ans

select 
    customer_id,
    sum(quantiy) as total_items
from sales_data
group by customer_id
having sum(quantiy) > 10;

--  10. Find the most expensive transaction.
-- ans

select transactions_id,max(total_sale)as max_sale from sales_data
group by transactions_id
order by max_sale desc
limit 1;

