
-- Q1. Find the total qty generated in 2023 from the sales_data table.
-- ans;- 
select customer_id,category, sum(quantiy) as total_quantity 
from sales_data 
where extract(year from sale_date)='2023'
Group by customer_id,category;

-- Q2.
-- Calculate total sales per month.
-- ans
select sum(total_sale) as all_sales , extract(month from sale_date) as month_sale
from sales_data
group by month_sale 
order by month_sale asc;

-- Q3.
-- Find the price_per_unit for each transactions id
-- ans
select avg(price_per_unit) as avg_pp_unit,transactions_id
 from sales_data 
 group by transactions_id;

-- Q4.
-- Calculate the lowest price_per_unit generated by category.
-- ans
select min(price_per_unit) as lowest_pp_unit,category 
from sales_data
group by category;

-- Q5. Calculate the highest price_per_unit generated by category.
-- ans
select max(price_per_unit) as highest_pp_unit,category 
from sales_data
group by category;


-- Q6.
-- Find the total number of unique customers as per category.
-- ans
select count(distinct(customer_id)) as unq_id, category
from sales_data
group by category;

-- Q7 find  all transactions where the category is 'Clothing' and the quantity sold is more than 2 in the month of Nov-2022
-- ans
select transactions_id,category,quantiy,sale_date
from sales_data where category='clothing'and
quantiy >2 and extract(year from sale_date) = 2022 and
extract(month from sale_date) = 11;

-- Q8.
-- Find customers who joined in 2023.
-- ans
select distinct(customer_id) ,sale_date from sales_data
where  extract(year from sale_date)= 2023;

-- Q9.
-- Calculate avg spending per customer per category of gender female only
-- ans
select customer_id,gender,category, round(avg(total_sale),2) as avg_spending from sales_data
where gender = 'female'
group by customer_id,category;

-- Q10.
-- Find the top 5 customers who spent the most money.
-- ans
select customer_id,sum(total_sale)  as all_spent from sales_data
group by customer_id
order by all_spent desc
limit 5;
